# Generated by Django 5.2 on 2025-05-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='availability_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='availability_start_date',
            field=models.DateTimeField(),
        ),
    ]
