# Generated by Django 5.2 on 2025-05-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0002_alter_applyjob_availability_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='availability_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='availability_start_date',
            field=models.DateField(),
        ),
    ]
