# Generated by Django 5.2 on 2025-05-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0003_alter_applyjob_availability_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='job_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('inteview', 'Selected for interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
