# Generated by Django 5.2.1 on 2025-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0004_alter_applyjob_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
