# Generated by Django 5.2.1 on 2025-05-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0005_alter_createjob_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='applicationDeadline',
            field=models.DateField(default='2025-06-25'),
        ),
        migrations.AddField(
            model_name='createjob',
            name='jobType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='createjob',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='applyjob',
            unique_together={('user', 'job')},
        ),
    ]
