# Generated by Django 5.2.1 on 2025-05-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0006_createjob_applicationdeadline_createjob_jobtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='applicationDeadline',
            field=models.DateField(default=None),
        ),
    ]
