# Generated by Django 5.2.1 on 2025-05-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0007_alter_createjob_applicationdeadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='applicationDeadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='jobType',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('co-op', 'Co-op')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('in-person', 'In Person')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('parent', 'Parent')], max_length=10),
        ),
    ]
